name: demo
on:
  workflow_dispatch:
    inputs:
      branch_name:
          description: 'Name of the branch'
          required: true
          default: 'main'
            
      perform_deploy_qa:
          description: 'Want to deploy to QA'
          required: true
          type: boolean
          default: false
        
      perform_deploy_prod:
          description: 'Want to deploy to Prod'
          required: true
          type: boolean
          default: false
        
      version:
          type: choice
          description: Version for Prod release
          options: 
           - major
           - minor
           - patch
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
  pull_request:
    types: [opened, reopened, edited, closed]
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
        
env:
  BRANCH_NAME: '${{ github.event.inputs.branch_name || github.head_ref || github.ref_name  }}'
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Run tests
        run: echo "Branch name is $BRANCH_NAME"
      - name: Echo
        run: |
            echo "Version selected is, ${{ github.event.inputs.version }}!"
            echo "- qa ${{ inputs.perform_deploy_qa }}!"
      - name: Echo
        run: |
            echo "Version selected is, ${{ github.event.inputs.version }}!"
            echo "- qa ${{ inputs.perform_deploy_qa }}!"
            
      - name: Call the Build bash script for QA
        run:  bash ${GITHUB_WORKSPACE}/scripts/read-logs.sh
