name: Test env
on:
  pull_request:
    types: [closed]
    branches:
      - gha-test
    paths-ignore:
      - index.html
env:
  SOME_SECRET: ${{ secrets.SOME_SECRET }}

jobs:
  env-test:
    name: Env tests
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '17'
      - run: java HelloWorldApp.java
